### ISSUE TITLE
incompatible node versions  v10 and v14 in dependencies [bug]

### ISSUE THREAD

**Issue by cassiodourado1** [workadventure/map-starter-kit#48]
on starter project using node 16 has showing this error: 

```
error nes.css@2.3.0: The engine "node" is incompatible with this module. Expected version "10.x". Got "16.17.0"
error Found incompatible module.
```

but, on usage node 10 present this error: 
```
error postcss-loader@7.0.2: The engine "node" is incompatible with this module. Expected version ">= 14.15.0". Got "10.24.1"
error Found incompatible module.
```
how to fix this problem?

**Comment by nolway** [comment]
Hello, thank you for your feedback! This is not a blocking error you can use the starter kit even if this error is displayed.
In the near futur, we're going to remove the nes.css dependency.
